envSecret:
  enabled: true

healthcheck:
  path: /actuator/health

# Add proper probe configuration for startup timing
probes:
  startup:
    enabled: true
    path: /actuator/health
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6  # Allow 60 seconds (6 * 10s) for startup
    successThreshold: 1
  
  liveness:
    enabled: true
    path: /actuator/health
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  
  readiness:
    enabled: true
    path: /actuator/health
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
