name: "Docs as Code - Confluence"
description: "Publish the content of a folder to confluence"
inputs:
  folder:
    description: "Folder containing the documentation to publish."
    required: true
  username:
    description: "Confluence username or email"
    required: true
  password:
    description: "Confluence password or API key"
    required: true
  confluence-base-url:
    description: "Your Confluence url"
    required: true
  space-key:
    description: "Confluence space key to publish the documentation"
    required: true
  parent-page-id:
    description: "Page id under which the documentation will be published"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run MD to Confluence #TODO: Implement this step
      shell: bash
      run: |
        echo "Running MD2C..."
        echo "Implementation pending..."
      continue-on-error: true