name: 'Markdown to Confluence Publisher'
description: 'Automatically publish markdown files to Confluence using md2conf'
author: 'Philip Rubbo'

inputs:
  markdown-path:
    description: 'Path to the markdown file or directory to publish'
    required: true
  confluence-domain:
    description: 'Confluence domain (e.g., mycompany.atlassian.net)'
    required: true
  confluence-username:
    description: 'Confluence username/email'
    required: true
  confluence-api-key:
    description: 'Confluence API key'
    required: true
  confluence-space:
    description: 'Confluence space key'
    required: true
  confluence-root-page:
    description: 'Root page ID for creating new pages (optional)'
    required: false
  github-token:
    description: 'GitHub token for accessing repositories'
    required: false
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    
    - name: Run markdown to confluence publisher
      run: python ${{ github.action_path }}/main.py
      shell: bash
      env:
        INPUT_MARKDOWN_PATH: ${{ inputs.markdown-path }}
        INPUT_CONFLUENCE_DOMAIN: ${{ inputs.confluence-domain }}
        INPUT_CONFLUENCE_USERNAME: ${{ inputs.confluence-username }}
        INPUT_CONFLUENCE_API_KEY: ${{ inputs.confluence-api-key }}
        INPUT_CONFLUENCE_SPACE: ${{ inputs.confluence-space }}
        INPUT_CONFLUENCE_ROOT_PAGE: ${{ inputs.confluence-root-page }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}

branding:
  icon: 'upload'
  color: 'blue'
