name: "Docs as Code - Confluence"
description: "Publish the content of a folder to confluence using FastAPI and Python"
inputs:
  folder:
    description: "Folder containing the documentation to publish."
    required: true
  username:
    description: "Confluence username or email"
    required: true
  password:
    description: "Confluence password or API key"
    required: true
  confluence-base-url:
    description: "Your Confluence url"
    required: true
  space-key:
    description: "Confluence space key to publish the documentation"
    required: true
  parent-page-id:
    description: "Page id under which the documentation will be published"
    required: true
  dry-run:
    description: "Run in dry-run mode (don't actually publish)"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      shell: bash
      run: |
        pip install -r ${{ github.action_path }}/requirements.txt
    
    - name: Publish to Confluence
      shell: bash
      run: |
        python ${{ github.action_path }}/confluence_publisher.py \
          --folder "${{ inputs.folder }}" \
          --username "${{ inputs.username }}" \
          --password "${{ inputs.password }}" \
          --confluence-base-url "${{ inputs.confluence-base-url }}" \
          --space-key "${{ inputs.space-key }}" \
          --parent-page-id "${{ inputs.parent-page-id }}" \
          ${{ inputs.dry-run == 'true' && '--dry-run' || '' }}
