name: Call Docs Sync API

on:
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Docs Sync API
        id: api-call
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://prodeng-docs-synchronizer-dev.doh.vtxdev.net/publish"
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: |
            {
              "markdown_path": "docs/mermaid-test.md",
              "domain": "vertexinc.atlassian.net",
              "username": "Philip.Rubbo@vertexinc.com",
              "api_key": ${{ secrets.ATLASSIAN_TOKEN }},
              "space": "PRE",
              "root_page": "5687837271"
            }
          timeout: 300000
      
      - name: Display API Response
        run: |
          echo "API Response Status: ${{ steps.api-call.outputs.response }}"
          echo "API Response Headers: ${{ steps.api-call.outputs.headers }}"