on:
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read matrix JSON
        id: set-matrix
        run: |
          MATRIX=$(jq -c . < matrix.json)
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  call-shared:
    needs: generate-matrix
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
      max-parallel: 2
    uses: ./.github/workflows/docs_syncer.yaml
    with:
      markdown-path: ${{ matrix.markdown-path }}
      markdown-repo: ${{ matrix.markdown-repo }}
      confluence-space: ${{ matrix.confluence-space }}
      confluence-root-page: ${{ matrix.confluence-root-page }}
      job: ${{ matrix.job }}
    secrets: inherit
