name: Call Docs Sync API

on:
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Docs Sync API
        id: api-call
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://argocd-dev.doh.vtxdev.net/applications/prodeng-docs-synchronizer-development-cne-usw2-toolsdev01-blue/publish"
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: |
            {
              "markdown_path": "docs/mermaid-test.md",
              "domain": "vertexinc.atlassian.net",
              "username": "Philip.Rubbo@vertexinc.com",
              "api_key": "ATATT3xFfGF0o8WAOtnsaVL14d-ILdUYarMWRZ-rrJdejsVUVfwW0odeH47bZcu6TMszMn4jbYnJNOg9YWSBMnfM9n2gH6fHdsV6kpk8XHGE6KiOZkdQzBhKIJE7igORaPtMI5kHh-fBpoR7u0bxbT93rhmghJff8gZaXDglRTK_KaH1-MI76CM=7415EA16",
              "space": "PRE",
              "root_page": "5687837271"
            }
          timeout: 300000
      
      - name: Display API Response
        run: |
          echo "API Response Status: ${{ steps.api-call.outputs.response }}"
          echo "API Response Headers: ${{ steps.api-call.outputs.headers }}"