name: Call Docs Sync API

on:
  workflow_dispatch:

jobs:
  call-api:
    runs-on: arc-k8s-standard
    steps:
      - name: Test Health Endpoint First
        run: |
          echo "🏥 Testing health endpoint accessibility..."
          curl -v "https://prodeng-docs-synchronizer-dev.doh.vtxdev.net/health"
          echo ""
          echo "🧪 Testing basic connectivity to /publish endpoint..."
          curl -v -X POST "https://prodeng-docs-synchronizer-dev.doh.vtxdev.net/publish" \
            -H "Content-Type: application/json" \
            -d '{"markdown_path": "test"}' || echo "Expected error - testing connectivity only"

      - name: Log API Call Details
        run: |
          echo "🚀 Starting API call to docs sync service"
          echo "URL: https://prodeng-docs-synchronizer-dev.doh.vtxdev.net/publish"
          echo "Method: POST"
          echo "Timestamp: $(date -u)"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"
          
      - name: Call Docs Sync API
        id: api-call
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://prodeng-docs-synchronizer-dev.doh.vtxdev.net/publish"
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: |
            {
              "markdown_path": "docs/mermaid-test.md",
              "repository": "${{ github.repository }}",
              "ref": "${{ github.ref }}",
              "domain": "vertexinc.atlassian.net",
              "username": "Philip.Rubbo@vertexinc.com",
              "api_key": "${{ secrets.ATLASSIAN_TOKEN }}",
              "space": "PRE",
              "root_page": "5687837271"
            }
          timeout: 300000
      
      - name: Debug API Call Outputs
        if: always()
        run: |
          echo "🔍 Raw API Call Debug Information:"
          echo "outputs.response: '${{ steps.api-call.outputs.response }}'"
          echo "outputs.status: '${{ steps.api-call.outputs.status }}'"
          echo "outputs.headers: '${{ steps.api-call.outputs.headers }}'"
          echo "outputs.data: '${{ steps.api-call.outputs.data }}'"
          echo ""
          echo "🧪 Manual curl test with same payload:"
          curl -v -X POST "https://prodeng-docs-synchronizer-dev.doh.vtxdev.net/publish" \
            -H "Content-Type: application/json" \
            -d '{
              "markdown_path": "docs/mermaid-test.md",
              "repository": "${{ github.repository }}",
              "ref": "${{ github.ref }}",
              "domain": "vertexinc.atlassian.net", 
              "username": "Philip.Rubbo@vertexinc.com",
              "api_key": "test-key-redacted",
              "space": "PRE",
              "root_page": "5687837271"
            }' || echo "Curl test completed"
      
      - name: Log API Response Details
        run: |
          echo "📊 API Response Analysis:"
          echo "Response Status: ${{ steps.api-call.outputs.response }}"
          echo "HTTP Status: ${{ steps.api-call.outputs.status }}"
          echo "Response Headers: ${{ steps.api-call.outputs.headers }}"
          echo "Response Time: $(date -u)"
          echo ""
          echo "🔍 Debugging Information:"
          if [ "${{ steps.api-call.outputs.status }}" != "200" ]; then
            echo "❌ API call failed with status: ${{ steps.api-call.outputs.status }}"
            echo "Response body: ${{ steps.api-call.outputs.response }}"
          else
            echo "✅ API call successful"
            echo "Response body: ${{ steps.api-call.outputs.response }}"
          fi
          
      - name: ArgoCD Application Status Check
        if: always()
        run: |
          echo "🔍 Checking ArgoCD application status..."
          echo "Application: prodeng-docs-synchronizer-development-cne-usw2-toolsdev01-blue"
          echo "Environment: development"
          echo "Cluster: cne-usw2-toolsdev01-blue"
          echo "Expected URL: https://prodeng-docs-synchronizer-dev.doh.vtxdev.net"
          echo ""
          echo "📋 Next Steps for Debugging:"
          echo "1. Check ArgoCD console for application health"
          echo "2. Verify pod logs in Kubernetes"
          echo "3. Confirm health endpoint accessibility"
          echo "4. Check service and ingress configuration"