name: Example - Publish Documentation

on:
  push:
    branches: [ main ]
    paths: [ 'docs/**', 'README.md' ]

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Publish README to Confluence
        uses: PJR3179/markdown-to-confluence-action@v2
        with:
          markdown-path: 'README.md'
          confluence-domain: 'vertexinc.atlassian.net'
          confluence-username: ${{ secrets.CONFLUENCE_USERNAME }}
          confluence-api-key: ${{ secrets.CONFLUENCE_API_KEY }}
          confluence-space: 'ENGINEERING'
          confluence-root-page: '123456789'
      
      - name: Publish entire docs directory
        uses: PJR3179/markdown-to-confluence-action@v2
        with:
          markdown-path: 'docs/'
          confluence-domain: 'vertexinc.atlassian.net'
          confluence-username: ${{ secrets.CONFLUENCE_USERNAME }}
          confluence-api-key: ${{ secrets.CONFLUENCE_API_KEY }}
          confluence-space: 'DOCS'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          confluence-root-page: '987654321'
