on:
  workflow_call:
    inputs:
      markdown-path:
        required: true
        type: string
      confluence-space:
        required: true
        type: string
      confluence-root-page:
        required: true
        type: string

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Publish to Confluence
        uses: vertexinc/prodeng-md-to-confluence@main
        with:
          markdown-path: ${{ inputs.markdown-path }}
          confluence-domain: 'vertexinc.atlassian.net'
          confluence-username: ${{ secrets.ATLASSIAN_USERNAME }}
          confluence-api-key: ${{ secrets.ATLASSIAN_TOKEN }}
          confluence-space: ${{ inputs.confluence-space }}
          confluence-root-page: ${{ inputs.confluence-root-page }}
